<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="com.plenom.BusylightSDK" Version="4.0.7" />
    <PackageReference Include="Microsoft.Extensions.Logging.Console" Version="8.0.0" />
    <PackageReference Include="Microsoft.SemanticKernel" Version="1.77.0" />
    <PackageReference Include="Microsoft.SemanticKernel.Connectors.AzureAIInference" Version="1.77.0-beta" />
    <PackageReference Include="Microsoft.SemanticKernel.Connectors.MistralAI" Version="1.77.0-alpha" />
    <PackageReference Include="System.Memory.Data" Version="10.0.3" />
  </ItemGroup>

</Project>
